[package]
name = "Rusty_Pi"
version = "0.1.0"
authors = ["David Hutchinson <dhutchinson@core-tt.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
